# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: bxxhbxxh
      MYSQL_DATABASE: cebs
    ports:
      - 127.0.0.1:3305:3306
    volumes:
      - ../db/:/var/lib/mysql
    networks:
      - cebs_app
  hst:
      container_name: hst
      build: ./hst/
      volumes:
        - ../huicloud:/code
      ports:
        - "127.0.0.1:7999:7999"
      links:
        - db
      entrypoint: "bash /wait-for-it.sh db:3306 -- /docker-entrypoint.sh"
      environment:
        PYTHONPATH: /code/:/code/hst:/code/DjoSiteDba
      depends_on:
        - db
      networks:
        - cebs_app
  tup:
    container_name: tup
    build: ./tup/
    volumes:
      - ../med:/code
    links:
      - hst
      - db
      - mqtt
    environment:
        PYTHONPATH: /code/tup/
        REDISHOST: redis
    entrypoint: "bash /wait-for-it.sh hst:7999 -- bash /wait-for-it.sh mqtt:1883 -- bash /wait-for-it.sh redis:6379 -- /docker-entrypoint.sh"
    depends_on:
      - hst
      - redis
    networks:
      - cebs_app
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - cebs_app
  dbadmin:
    image: adminer
    container_name: dbadmin
    restart: always
    ports:
      - 8088:8080
    networks:
      - cebs_app
  mqtt:
    build: ./mqtt    
    container_name: mqtt
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - cebs_app
  ui:
    build: ./ui
    container_name: ui
    depends_on:
      - mqtt
    volumes:
      - ../www:/code
    entrypoint: "bash /docker-entrypoint.sh"
    ports:
      - 7589:8888
    networks:
      - cebs_app
networks:
  cebs_app:
    driver: bridge
