FROM node
# VOLUME /rootfs
VOLUME [ "/rootfs" ]
Add package.json /
Run npm install 
Add docker-entrypoint.sh  /
RUN chmod +x /docker-entrypoint.sh
# ENV PATH="=/home/node/.npm-global/bin:${PATH}"
WORKDIR /code/zhmed/jsserver



